# Generated by Django 5.2.5 on 2026-02-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_galeria', models.CharField(blank=True, max_length=255)),
                ('url_manual', models.URLField(blank=True)),
                ('texto_direccion', models.TextField(blank=True)),
                ('iframe_mapa', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('imagen_manual', models.ImageField(blank=True, null=True, upload_to='manuales/')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('portada', models.ImageField(upload_to='eventos/')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('url', models.URLField(blank=True, help_text='URL externa de la noticia. Si se deja vacío, al hacer clic se abrirá la imagen directamente.', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField()),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.contenidoinicio')),
            ],
            options={
                'unique_together': {('contenido', 'orden')},
            },
        ),
    ]
