# Generated by Django 5.2.5 on 2026-03-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='galleryimage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='iframe_mapa',
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='imagen_manual',
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='texto_direccion',
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='titulo_galeria',
        ),
        migrations.RemoveField(
            model_name='contenidoinicio',
            name='url_manual',
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='hero_imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='hero_imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='hero_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='galeria/'),
        ),
    ]
