# Generated by Django 5.2.5 on 2026-03-13 19:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título opcional de la noticia.', max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url',
            field=models.URLField(blank=True, help_text='Si añades un link, al hacer clic en la imagen se abrirá esa URL. Si lo dejas vacío, la imagen se ampliará.', null=True, verbose_name='Link (opcional)'),
        ),
    ]
