# Generated by Django 5.2.5 on 2026-03-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_galleryimage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoinicio',
            name='iframe_mapa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='imagen_manual',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='texto_direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='titulo_galeria',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='url_manual',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url',
            field=models.URLField(blank=True, help_text='URL externa de la noticia. Si se deja vacío, al hacer clic se abrirá la imagen.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='galleryimage',
            unique_together={('contenido', 'orden')},
        ),
    ]
