# Generated by Django 5.2.5 on 2026-02-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_galleryimage_options_galleryimage_orden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('portada', models.ImageField(upload_to='eventos/')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={},
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='texto_direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='orden',
            field=models.PositiveIntegerField(),
        ),
    ]
