# Generated by Django 5.2.5 on 2026-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_evento_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumno', models.IntegerField()),
                ('nombre_padre', models.CharField(max_length=255)),
                ('email_padre', models.EmailField(max_length=254)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('banco', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('estado_pago', models.CharField(max_length=50)),
                ('referencia_pago', models.CharField(max_length=100)),
            ],
        ),
    ]
