# Generated by Django 5.2.5 on 2026-02-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_padre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Padre',
        ),
    ]
