# Generated by Django 5.2.7 on 2026-02-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_padre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Padre',
        ),
    ]
