# Generated by Django 5.2.5 on 2026-02-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_noticia_delete_padre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='enlace',
        ),
        migrations.AddField(
            model_name='noticia',
            name='url_name',
            field=models.CharField(blank=True, help_text='Ej: core:nosotros, core:noticias', max_length=100),
        ),
    ]
