# Generated by Django 5.2.5 on 2026-02-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_noticia_enlace_noticia_url_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='url_name',
            new_name='enlace',
        ),
    ]
