# Generated by Django 5.2.5 on 2026-02-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_url_name_noticia_enlace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='enlace',
            new_name='url_name',
        ),
    ]
