# Generated by Django 5.2.5 on 2026-02-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_padre'),
        ('core', '0011_rename_enlace_noticia_url_name'),
    ]

    operations = [
    ]
