# Generated by Django 5.2.5 on 2026-03-13 21:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteLudica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.OneToOneField(help_text='Estudiante del sistema principal', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_ludica', to='estudiantes.estudiante')),
                ('user', models.OneToOneField(blank=True, help_text='Cuenta de acceso para el estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante_ludica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante en Lúdicas',
                'verbose_name_plural': 'Estudiantes en Lúdicas',
                'ordering': ['estudiante__apellidos'],
            },
        ),
        migrations.CreateModel(
            name='ProfesorLudica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(help_text='Número de documento (solo dígitos)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Solo números.')])),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('especialidad', models.CharField(blank=True, help_text='Área o especialidad del docente (ej: Arte, Deportes, Música)', max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, help_text='Cuenta de acceso al sistema (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesor_ludica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor de Lúdica',
                'verbose_name_plural': 'Profesores de Lúdicas',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Ludica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('grados_permitidos', models.JSONField(default=list, help_text='Lista de grados que pueden inscribirse en esta lúdica')),
                ('cupo_maximo', models.PositiveIntegerField(default=30, help_text='Número máximo de estudiantes')),
                ('horario', models.CharField(blank=True, help_text='Ej: Lunes y Miércoles 2:00 - 4:00 PM', max_length=200)),
                ('lugar', models.CharField(blank=True, help_text='Aula, cancha, sala, etc.', max_length=150)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('COMPLETA', 'Cupo completo')], default='ACTIVA', max_length=10)),
                ('icono', models.CharField(blank=True, default='fa-star', help_text='Clase de icono Font Awesome (ej: fa-music, fa-futbol)', max_length=50)),
                ('color', models.CharField(blank=True, default='#4f46e5', help_text='Color hex de la tarjeta (ej: #4f46e5)', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(blank=True, help_text='Docente responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ludicas', to='ludicas.profesorludica')),
            ],
            options={
                'verbose_name': 'Lúdica',
                'verbose_name_plural': 'Lúdicas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas del administrador')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='ludicas.estudianteludica')),
                ('ludica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='ludicas.ludica')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('estudiante', 'ludica')},
            },
        ),
    ]
