# Generated by Django 5.2.7 on 2026-02-12 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del módulo (ej: Lúdicas)', max_length=100)),
                ('app_label', models.CharField(help_text='Nombre técnico de la app Django (ej: ludicas)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del módulo')),
                ('activo', models.BooleanField(default=True, help_text='Define si el módulo está activo en el sistema')),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono (ej: fa-calendar para Font Awesome)', max_length=50)),
                ('url_base', models.CharField(blank=True, help_text='URL base del módulo (ej: /ludicas/)', max_length=100)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización en menús')),
                ('roles_permitidos', models.CharField(default='ADMINISTRADOR', help_text='Roles que pueden acceder (separados por coma: ADMINISTRADOR,PADRE)', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Módulo del Sistema',
                'verbose_name_plural': 'Módulos del Sistema',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParametroGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del parámetro (ej: fecha_corte_ludicas)', max_length=100, unique=True)),
                ('valor', models.CharField(help_text='Valor del parámetro', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de qué hace este parámetro')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetro Global',
                'verbose_name_plural': 'Parámetros Globales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('PADRE', 'Padre')], default='PADRE', help_text='Rol del usuario en el sistema', max_length=30)),
                ('activo', models.BooleanField(default=True, help_text='Define si el usuario puede acceder al sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('padre', models.OneToOneField(blank=True, help_text='Vinculación con el modelo Padre (solo si rol = PADRE)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_usuario', to='padres.padre')),
                ('user', models.OneToOneField(help_text='Usuario de Django asociado', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='LogAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('VER', 'Visualización'), ('EXPORTAR', 'Exportación'), ('OTRO', 'Otra acción')], default='OTRO', max_length=20)),
                ('accion', models.CharField(help_text='Descripción de la acción realizada', max_length=255)),
                ('modulo', models.CharField(blank=True, help_text='Módulo donde se realizó la acción', max_length=100)),
                ('detalles', models.TextField(blank=True, help_text='Información adicional de la acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acción',
                'verbose_name_plural': 'Logs de Acciones',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='plataforma__fecha_088692_idx'), models.Index(fields=['usuario', '-fecha'], name='plataforma__usuario_381e81_idx')],
            },
        ),
    ]
