# Generated by Django 5.2.5 on 2026-03-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_galeria', models.CharField(blank=True, max_length=255)),
                ('url_manual', models.URLField(blank=True)),
                ('texto_direccion', models.TextField(blank=True)),
                ('iframe_mapa', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('imagen_manual', models.ImageField(blank=True, null=True, upload_to='manuales/')),
                ('hero_imagen1', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('hero_imagen2', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('hero_video', models.URLField(blank=True)),
            ],
        ),
    ]
