# Generated by Django 5.2.5 on 2026-03-13 19:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidoinicio',
            name='hero_imagen1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero1'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='hero_imagen2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero2'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='imagen_manual',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='manual'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='noticia'),
        ),
    ]
