# Generated by Django 5.2.5 on 2026-03-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_alter_contenidoinicio_hero_imagen1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidoinicio',
            name='hero_imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='hero_imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='imagen_manual',
            field=models.ImageField(blank=True, null=True, upload_to='manuales/'),
        ),
        migrations.AlterField(
            model_name='contenidoinicio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
