# Generated by Django 5.2.5 on 2026-03-16 19:26

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_contenidoinicio_hero_imagen1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
