# Generated by Django 5.2.5 on 2026-03-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_cambiar_url_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.TextField(),
        ),
    ]
