# Generated by Django 5.2.5 on 2026-03-17 13:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_alter_noticia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('directivas', 'Directivas'), ('coordinadores', 'Coordinadores'), ('docentes', 'Docentes'), ('administrativos', 'Administrativos'), ('servicios', 'Servicios Generales')], max_length=20)),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
            ],
        ),
    ]
