# Generated by Django 5.2.5 on 2026-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='descripcion_back',
            field=models.TextField(blank=True, null=True),
        ),
    ]
