# Generated by Django 5.2.7 on 2026-02-06 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(help_text='Documento de identidad del estudiante', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El documento solo debe contener números.', regex='^[0-9]+$')])),
                ('fecha_nacimiento', models.DateField(help_text='Formato: AAAA-MM-DD')),
                ('grado', models.CharField(help_text='Ejemplo: 5to grado, Primero de secundaria', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('padre', models.ForeignKey(help_text='Padre responsable del estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='padres.padre')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
