# Generated by Django 5.2.5 on 2026-02-05 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(error_messages={'unique': 'Ya existe un padre registrado con este correo.'}, max_length=254, unique=True)),
                ('documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El documento solo debe contener números.', regex='^[0-9]+$')])),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
